import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Muhammad Fareed | Full-Stack Developer',
  description:
    "Hello, I'm Fareed. I am a full-stack developer from Pakistan. I enjoy building modern web and mobile applications using React, Next.js, Node.js, and MongoDB.",
  keywords: [
    'Muhammad Fareed',
    'Full-stack developer',
    'Pakistan',
    'React',
    'Next.js',
    'Node.js',
    'Express.js',
    'MongoDB',
    'Supabase',
    'Tailwind CSS',
    'Web development',
    'Frontend',
    'Backend',
    'Portfolio',
    'JavaScript',
    'TypeScript',
    'UI/UX',
    'Software Engineer',
    'Angular',
    'PostgreSQL',
    'Redux',
    'CSS3',
    'HTML5',
    'REST API',
    'JavaScript ES6',
    'Socket.IO',
    'Firebase',
    'React Native',
  ],
  url: env.SITE_URL || 'https://yourdomain.com',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
